# Generated by Django 4.2.21 on 2025-06-24 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('trim_size', models.CharField(max_length=50)),
                ('page_count', models.PositiveIntegerField()),
                ('binding_type', models.CharField(max_length=100)),
                ('interior_type', models.CharField(max_length=100)),
                ('paper_type', models.CharField(max_length=100)),
                ('cover_finish', models.CharField(max_length=100)),
                ('interior_file', models.TextField()),
                ('cover_file', models.TextField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved')], default='Draft', max_length=20)),
                ('price_per_unit', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
