# Generated by Django 4.2.21 on 2025-06-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='account_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('enterprise', 'Enterprise')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='resale_cert_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='shipping_state',
            field=models.CharField(default='TX', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='tax_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='tax_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='price_per_unit',
            field=models.FloatField(default=0),
        ),
    ]
