# Generated by Django 4.2.23 on 2025-06-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_type', models.CharField(max_length=50)),
                ('spine_type', models.CharField(blank=True, max_length=20)),
                ('exterior_color', models.CharField(blank=True, max_length=30)),
                ('foil_stamping', models.CharField(blank=True, max_length=30)),
                ('screen_stamping', models.CharField(blank=True, max_length=30)),
                ('corner_protector', models.CharField(blank=True, max_length=50)),
                ('interior_color', models.CharField(max_length=30)),
                ('paper_type', models.CharField(max_length=50)),
                ('trim_size', models.CharField(max_length=50)),
                ('base_price', models.FloatField()),
                ('spine_price', models.FloatField(default=0)),
                ('exterior_price', models.FloatField(default=0)),
                ('foil_price', models.FloatField(default=0)),
                ('screen_price', models.FloatField(default=0)),
                ('corner_price', models.FloatField(default=0)),
                ('interior_price_per_page', models.FloatField()),
                ('paper_price_per_page', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
                ('tax_rate', models.FloatField(help_text='Decimal tax rate e.g. 0.0825 for 8.25%')),
            ],
        ),
    ]
