# Generated by Django 4.2.21 on 2025-06-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_bindingtype_cornerprotector_exteriorcolor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrimSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='foilstamping',
            old_name='color',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='screenstamping',
            name='color',
        ),
        migrations.AddField(
            model_name='screenstamping',
            name='name',
            field=models.CharField(default='Golden', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bindingtype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cornerprotector',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='exteriorcolor',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='foilstamping',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='interiorcolor',
            name='price_per_page',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='papertype',
            name='price_per_page',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='screenstamping',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='spinetype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
