# Generated by Django 4.2.21 on 2025-06-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_trimsize_rename_color_foilstamping_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
